name: Batch Update WeChat Articles

on:
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes
  workflow_dispatch:  # Allow manual triggering

# Ensure only one workflow runs at a time
concurrency:
  group: batch-update
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 9  # Set timeout to 9 minutes (GitHub Actions max is 360 minutes)
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Process batch of articles
        env:
          WECHAT_BIZ_ID: ${{ secrets.WECHAT_BIZ_ID }}
          WECHAT_TOKEN: ${{ secrets.WECHAT_TOKEN }}
          WECHAT_COOKIE: ${{ secrets.WECHAT_COOKIE }}
        run: node src/batch-process.js

      - name: Commit and push if changes exist
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update WeChat articles batch $(date +'%Y-%m-%d %H:%M:%S')" && git push)
