name: Batch Update WeChat Articles

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
  workflow_dispatch:  # Allow manual triggering

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: write
  pages: write
  id-token: write

# Ensure only one workflow runs at a time
concurrency:
  group: batch-update
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 9  # Set timeout to 9 minutes (GitHub Actions max is 360 minutes)
    env:
      TRIGGER_TIME: ${{ github.event.schedule }}
      EVENT_NAME: ${{ github.event_name }}
      REF_NAME: ${{ github.ref_name }}
      REPOSITORY: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Debug workflow trigger
        run: |
          echo "Trigger time: $TRIGGER_TIME"
          echo "Event name: $EVENT_NAME"
          echo "Branch: $REF_NAME"
          echo "Repository: $REPOSITORY"
          echo "Current time: $(date)"

      - name: Process batch of articles
        env:
          WECHAT_BIZ_ID: ${{ secrets.WECHAT_BIZ_ID }}
          WECHAT_TOKEN: ${{ secrets.WECHAT_TOKEN }}
          WECHAT_COOKIE: ${{ secrets.WECHAT_COOKIE }}
        run: node src/batch-process.js

      - name: Commit and push if changes exist
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          # Stage changes
          git add public/ data/
          # Commit and push if there are changes
          if ! git diff --quiet HEAD || ! git diff --staged --quiet; then
            git commit -m "Batch update: Generate pages for articles ($(date +'%Y-%m-%d %H:%M:%S'))"
            # Pull latest changes with rebase right before push
            git pull origin main --rebase
            git push origin main
          else
            echo "No changes to commit"
          fi
